version: '3'

services:
  jekyll-ngnix:
    image: docker.nexus.archi-lab.io/archilab/fae-documentation-server:${TAG}
    ports:
      - 80:80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
